### ISSUE TITLE
Is it possible to blur site's contents instead of desktop behind titlebar?

### ISSUE THREAD

**Issue by emvaized** [manilarome/blurredfox#16]
Very awesome appearance!
My only question is - is it possible to achieve behaviour similar to Safari on Mac OS?
E.g. title bar blures site's content behind it, and not desktop content.

![screen record to illustrate](https://user-images.githubusercontent.com/37851576/90037316-bd902100-dccc-11ea-850b-cb11e3634e93.gif)

**Comment by manilarome** [comment]
I'm not really sure if you can achieve this by just using CSS. But I think this is better/more beautiful than rendering the desktop. Yeah, this is a nice suggestion/question but I don't know how to implement this. Patches welcome, of course.

**Comment by manilarome** [comment]
So it turns out that you can do this by just using CSS:

![image](https://user-images.githubusercontent.com/40349590/90078724-5c9e3280-dd38-11ea-84fc-c74a7ec3feef.png)

Change the `#nav-bar` to

```css
toolbar#nav-bar {
	background: var(--bf-navbar-bg) !important;
	padding: var(--bf-navbar-padding) !important;
	position: absolute !important;
	z-index: 99999 !important;
	margin-bottom: -50px !important;
	backdrop-filter: blur(20px) !important;
	
	/* Remove horizontal line on navbar */
	box-shadow: none !important;
	border-top: none !important;
}
```

The problem with this is that if the website has navigation bar, firefox' navbar will hide it.

**Comment by emvaized** [comment]
@manilarome 
Sorry, can't confirm it working because I'm still trying to make whole thing work on Mac :))
But looks very promising on your screenshots!

**Comment by emvaized** [comment]
As for Safari - on Reddit navbar is always showing under the panel, like this: 
![reddit navbar](https://user-images.githubusercontent.com/37851576/90080775-2e0e6080-dd14-11ea-8860-679ca392108b.gif)

But I guess it won't tell you a lot. 
What I found more interesting, is how it's handled on Ukrainian site called [Olx](olx.ua) - there we have auto-hiding navbar, and in Safari it goes completely under the panel when hidden:

![Запись экрана 2020-08-13 в 03 17 40](https://user-images.githubusercontent.com/37851576/90080904-86ddf900-dd14-11ea-89df-a9fa80e9dd41.gif)

**Comment by manilarome** [comment]
> I'm still trying to make whole thing work on Mac :))

Sorry about the lack of mac support. Good luck!

How safari handle the navbars are interesting. I'll look more into it. Maybe we can find a hack/way to implement this.

**Comment by manilarome** [comment]
I think this is a better implementation:

```css
#navigator-toolbox {
	position: absolute !important;;
	overflow: visible !important;
	z-index: 99999;
	backdrop-filter: blur(6px) !important;
}
	
#browser {
	margin-top: -100px !important;
}
```

![image](https://user-images.githubusercontent.com/40349590/90088162-ec4fdb00-dd50-11ea-9587-d61b1db5a40b.png)

Anyway, please consider requesting a PR if you are able to make this theme work on macOS.
