### ISSUE TITLE
Background blur not showing with picom and blurred styles

### ISSUE THREAD

**Issue by KiranWells** [manilarome/blurredfox#48]
I recently installed this onto Firefox Developer Edition, and my background is not showing through the window. All other blurs seem to work fine, but the main window will not be transparent. I have picom and blur enabled, and I have changed all the required settings in `about:config`. In addition, I even tried going into the remote debugger, and using:

```css
* {
  background-color: transparent !important;
}
```
the main window remains solid. 

What appears to be happening is that a gray-blue background is being shown, even with everything else transparent. This is visible behind the navbar and in the margins around `#browser` if I increase them.

The `html:body` element is visibly changed when I set the background to `red` or something similar, but even when that is set to transparent, the `html#main-window` element behind it is not shown (if it has a color of `red`, the color remains gray-blue).

![blurredfox-issue](https://user-images.githubusercontent.com/64935184/103727092-001a0900-4fa0-11eb-92ed-c6d31827c732.jpg)

Thanks for the help!

**Comment by Mange** [comment]
I have the same issue with Developer Edition. Everything was fine, then I reinstalled my OS on a new drive, rsynced my `~`, and started again. After installing Firefox the background was no longer blurred (while the layout is still clearly blurredfox).

I've tried reinstalling blurredfox many times, with restarts and different themes selected before and after installing. Still nothing.

I was unsure if the problem was caused by a recent update to Firefox (I had not updated my old install in a few weeks), or something in the new system - so I was waiting to report it until I would have gotten more time at it.

That you also have this problem now adds credence to it being a Firefox update causing this IMO.

**Comment by KiranWells** [comment]
Update: Developer is still not working, but normal Firefox is. However, I found a (somewhat hacky) workaround to get the blur effect. If you set the `#browser` background to your wallpaper, and set the other elements to blur, it should work.
```css
#browser {
  margin-top: -100px;
  padding-top: 100px; /* to put the image under the toolbar */
  background-image: url(file:///home/user/wallpapers/wallpaper.jpg);
  background-size: cover;
  background-position: center;
}

#browser>* {
  backdrop-filter: blur(var(--bf-backdrop-blur));
}
```
![blurredfox-issue-fix](https://user-images.githubusercontent.com/64935184/103826423-6c4a4a80-503c-11eb-8e2b-d571cfbb9307.jpg)

(Just FYI this image includes some other changes that I added to make more things consistent, and the new tab page is [nightTab](https://github.com/zombieFox/nightTab) using that same strategy.)

**Comment by PoorPocketsMcNewHold** [comment]
Pretty strange, as the whole blurring is done by the compositor in itself. As recent picom updates support transparent windows _(And blurring after merging the dual-kawase blur)_
The main issue would be that Firefox doesn't show transparent then really not able to call for the blur effect.

**Comment by KiranWells** [comment]
Just to clarify; the issue does not seem to be picom at all. Transparent windows are working just as they should, as you can see in the screenshot of normal FIrefox. The problem is that Developer has a solid background that I cannot remove.

**Comment by lvx-tenebris** [comment]
How should  i go about doing this? Should I just add the snippet of code? Or should i find it? I can't find it on the remote debugger, can anyone help? Thanks in advance.

Update: So, i was able to implement Transparency using the snippet, but no blur has been applied (i have picom with blur applied). Any sugestions?

**Comment by KiranWells** [comment]
Which snippet do you mean? I was not aware of a fix for this.

**Comment by jstawik** [comment]
Can confirm - using picom and regular firefox - upon rolling back to FF84 transparency works. It breaks in FF85. The workaround @KiranWells  suggested is just putting the image in the background of the browser - it won't match up with your actual wallpaper, won't show the windows underneath and most importantly - picom won't apply it's blur. It's as if from the compositor point of view this area wasn't transparent at all. 
I have tested this earlier with a more minimal snippet:
```css
html, html > *, html > * > *, .browser-toolbar  {
  border: none !important;
  -moz-appearance: none !important;
  box-shadow: none !important;
  background: transparent!important;
}

.titlebar-color, .browser-toolbar, findbar {
  background: rgba(22,22,22, 0.75)!important;  
}

.tab-line {
  background: none !important;
}

.tab-background[selected=true] {
  background: #402222 !important;
  border-radius: 6px;
  border: none !important;
}

tab[selected="true"]::after, .tabbrowser-tab[beforeselected-visible]::after {
    opacity: 0.75 !important;
}

/*   rgba(49, 54, 59, 0.75) */
```
and it is also broken by FF85.
Screenshots for comparison: 
FF84  https://imgur.com/a/GucXS6u
FF85 -  https://i.imgur.com/SBHTLnE.png
while the theme in the screenshots is not blurredfox, it showcases the more minimal scenario for recreating this issue.
