### ISSUE TITLE
macOS Compatibility ( Experience / FYI )

### ISSUE THREAD

**Issue by typkrft** [manilarome/blurredfox#8]
Sadly, on macOS the transparency and blur do not work in most places, the layout does work. I believe some of this could work with `-moz-appearance: -moz-mac-vibrancy-dark`. Regardless thank you for the clearly laid out themes.

Edit:
```css
#main-window {
	-moz-appearance: -moz-mac-vibrancy-dark !important;
	border: none !important;
}
```
Resolves the URL Bar, Tab Bar, Sidebar.
